# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37a9a0250d92540487f928e6127cd8f4da46a2d6865a5b708a27c9c90b0be4464074a332445a28e2a921525c70ccc407f248106d4916987be5c33b65ca9c9d0d

test:
  secret_key_base: 614fc387ce901007ec487e3b5afea6ddb05b6465bab462b5cb089becbd184aa302b795863e887f39344dc6bf37faab02751a73d319f32bcfad739e0a3c359086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
